// Example designs built only from the deterministic operations, the same
// way Claude builds them. The record console is the acceptance test in
// docs/TESTING.md, and the app can load it as a starting point.

import type { Op } from "./ops.js";

export function recordConsoleOps(): Op[] {
  const sideZ = { start: { at: "0" }, size: "top_depth" };
  return [
    { op: "rename_design", name: "Record console" },
    { op: "set_param", name: "top_length", expr: "2040", unit: "mm", min: 1200, max: 2400, step: 10, note: "Length of the top" },
    { op: "set_param", name: "top_depth", expr: "520", unit: "mm", min: 350, max: 600, step: 5 },
    { op: "set_param", name: "carcass_height", expr: "400", unit: "mm", min: 340, max: 700, step: 5, note: "Sides, floor to the underside of the top" },
    { op: "set_param", name: "drawers", expr: "5", unit: "count", min: 2, max: 6, step: 1 },
    { op: "set_param", name: "slide_gap", expr: "12.7", unit: "mm", min: 0, max: 20, step: 0.1, note: "Side-mount slides need 12.7 mm each side" },
    { op: "set_param", name: "lp_clear", expr: "320", unit: "mm", note: "12-inch LP sleeves are about 315 mm" },
    { op: "set_param", name: "front_gap", expr: "2", unit: "mm", min: 1, max: 4, step: 0.5 },

    {
      op: "define_material",
      id: "carcass_30",
      name: "30 mm carcass panel",
      kind: "sheet",
      thickness_mm: 30,
      grained: true,
      sheet_sizes_mm: [[2400, 1200]],
    },
    {
      op: "define_material",
      id: "top_30",
      name: "30 mm solid top",
      kind: "solid",
      thickness_mm: 30,
      grained: true,
      board_max_length_mm: 2400,
      board_max_width_mm: 600,
    },
    { op: "define_material", id: "ply15", name: "15 mm birch ply", kind: "sheet", thickness_mm: 15, grained: true, sheet_sizes_mm: [[2440, 1220]] },
    { op: "define_material", id: "ply9", name: "9 mm ply", kind: "sheet", thickness_mm: 9, grained: true, sheet_sizes_mm: [[2440, 1220]] },
    { op: "define_material", id: "ply6", name: "6 mm ply", kind: "sheet", thickness_mm: 6, grained: true, sheet_sizes_mm: [[2440, 1220]] },
    { op: "define_material", id: "front_18", name: "18 mm drawer-front panel", kind: "sheet", thickness_mm: 18, grained: true, sheet_sizes_mm: [[2400, 1200]] },

    // Carcass.
    {
      op: "add_panel",
      id: "left_side",
      name: "Left side",
      material: "carcass_30",
      thickness_axis: "x",
      grain_axis: "y",
      x: { start: { at: "0" } },
      y: { start: { at: "0" }, size: "carcass_height" },
      z: sideZ,
      tags: ["carcass", "side"],
    },
    {
      op: "add_panel",
      id: "right_side",
      name: "Right side",
      material: "carcass_30",
      thickness_axis: "x",
      grain_axis: "y",
      x: { end: { at: "top_length" } },
      y: { start: { at: "0" }, size: "carcass_height" },
      z: sideZ,
      tags: ["carcass", "side"],
    },
    {
      op: "add_panel",
      id: "bottom",
      name: "Bottom",
      material: "carcass_30",
      thickness_axis: "y",
      grain_axis: "x",
      x: { start: { face: "left_side.right" }, end: { face: "right_side.left" } },
      y: { start: { at: "0" } },
      z: sideZ,
      tags: ["carcass"],
    },
    {
      op: "add_panel",
      id: "top",
      name: "Top",
      material: "top_30",
      thickness_axis: "y",
      grain_axis: "x",
      x: { start: { at: "0" }, end: { at: "top_length" } },
      y: { start: { face: "left_side.top" } },
      z: sideZ,
      tags: ["top"],
    },
    {
      op: "add_panel",
      id: "back",
      name: "Back",
      material: "ply9",
      thickness_axis: "z",
      grain_axis: "x",
      x: { start: { face: "left_side.right" }, end: { face: "right_side.left" } },
      y: { start: { face: "bottom.top" }, end: { face: "top.bottom" } },
      z: { start: { at: "0" } },
      tags: ["carcass"],
    },
    {
      op: "set_param",
      name: "bay",
      expr: "(top_length - left_side.thickness - right_side.thickness - (drawers - 1) * 30) / drawers",
      unit: "mm",
      note: "Width of each drawer opening",
    },
    {
      op: "add_panel",
      id: "partition",
      name: "Partition",
      material: "carcass_30",
      thickness_axis: "x",
      grain_axis: "y",
      x: { start: { face: "left_side.right", offset: "bay" } },
      y: { start: { face: "bottom.top" }, end: { face: "top.bottom" } },
      z: { start: { face: "back.front" }, end: { at: "top_depth" } },
      tags: ["carcass", "partition"],
    },
    { op: "set_array", id: "partitions", parts: ["partition"], axis: "x", count: "drawers - 1", pitch: "bay + partition.thickness" },
    { op: "add_joint", id: "bottom_in_left", type: "rabbet", host: "left_side", guest: "bottom", depth: "10" },
    { op: "add_joint", id: "bottom_in_right", type: "rabbet", host: "right_side", guest: "bottom", depth: "10" },
    { op: "add_joint", id: "back_in_left", type: "groove", host: "left_side", guest: "back", depth: "10" },
    { op: "add_joint", id: "back_in_right", type: "groove", host: "right_side", guest: "back", depth: "10" },
    { op: "add_joint", id: "partition_in_bottom", type: "dado", host: "bottom", guest: "partition", depth: "10" },
    { op: "add_joint", id: "partition_to_top", type: "screws", host: "top", guest: "partition", count: 2 },
    { op: "add_joint", id: "top_to_left", type: "screws", host: "top", guest: "left_side", count: 3 },
    { op: "add_joint", id: "top_to_right", type: "screws", host: "top", guest: "right_side", count: 3 },

    // Now the partition exists, the bay can use its real thickness.
    {
      op: "set_param",
      name: "bay",
      expr: "(top_length - left_side.thickness - right_side.thickness - (drawers - 1) * partition.thickness) / drawers",
      unit: "mm",
      note: "Width of each drawer opening",
    },

    // One drawer, in the first bay. An array repeats it across the rest.
    {
      op: "add_panel",
      id: "false_front",
      name: "Drawer front",
      material: "front_18",
      thickness_axis: "z",
      grain_axis: "x",
      x: { start: { face: "left_side.right", offset: "front_gap" }, end: { face: "partition.left", offset: "-front_gap" } },
      y: { start: { face: "bottom.top", offset: "front_gap" }, end: { face: "top.bottom", offset: "-front_gap" } },
      z: { end: { at: "top_depth" } },
      tags: ["drawer", "drawer_front"],
    },
    {
      op: "add_panel",
      id: "drawer_side_l",
      name: "Drawer side, left",
      material: "ply15",
      thickness_axis: "x",
      grain_axis: "z",
      x: { start: { face: "left_side.right", offset: "slide_gap" } },
      y: { start: { face: "bottom.top", offset: "15" }, end: { face: "top.bottom", offset: "-15" } },
      z: { start: { face: "back.front", offset: "20" }, end: { face: "false_front.back" } },
      tags: ["drawer", "drawer_side"],
    },
    {
      op: "add_panel",
      id: "drawer_side_r",
      name: "Drawer side, right",
      material: "ply15",
      thickness_axis: "x",
      grain_axis: "z",
      x: { end: { face: "partition.left", offset: "-slide_gap" } },
      y: { start: { face: "drawer_side_l.bottom" }, end: { face: "drawer_side_l.top" } },
      z: { start: { face: "drawer_side_l.back" }, end: { face: "drawer_side_l.front" } },
      tags: ["drawer", "drawer_side"],
    },
    {
      op: "add_panel",
      id: "drawer_box_front",
      name: "Drawer box front",
      material: "ply15",
      thickness_axis: "z",
      grain_axis: "x",
      x: { start: { face: "drawer_side_l.right" }, end: { face: "drawer_side_r.left" } },
      y: { start: { face: "drawer_side_l.bottom" }, end: { face: "drawer_side_l.top" } },
      z: { end: { face: "drawer_side_l.front" } },
      tags: ["drawer", "drawer_end"],
    },
    {
      op: "add_panel",
      id: "drawer_box_back",
      name: "Drawer box back",
      material: "ply15",
      thickness_axis: "z",
      grain_axis: "x",
      x: { start: { face: "drawer_side_l.right" }, end: { face: "drawer_side_r.left" } },
      y: { start: { face: "drawer_side_l.bottom" }, end: { face: "drawer_side_l.top" } },
      z: { start: { face: "drawer_side_l.back" } },
      tags: ["drawer", "drawer_end"],
    },
    {
      op: "add_panel",
      id: "drawer_bottom",
      name: "Drawer bottom",
      material: "ply6",
      thickness_axis: "y",
      grain_axis: "z",
      x: { start: { face: "drawer_side_l.right" }, end: { face: "drawer_side_r.left" } },
      y: { start: { face: "drawer_side_l.bottom", offset: "10" } },
      z: { start: { face: "drawer_box_back.front" }, end: { face: "drawer_box_front.back" } },
      tags: ["drawer", "drawer_bottom"],
    },
    { op: "add_joint", id: "box_front_in_l", type: "dado", host: "drawer_side_l", guest: "drawer_box_front", depth: "5" },
    { op: "add_joint", id: "box_front_in_r", type: "dado", host: "drawer_side_r", guest: "drawer_box_front", depth: "5" },
    { op: "add_joint", id: "box_back_in_l", type: "dado", host: "drawer_side_l", guest: "drawer_box_back", depth: "5" },
    { op: "add_joint", id: "box_back_in_r", type: "dado", host: "drawer_side_r", guest: "drawer_box_back", depth: "5" },
    { op: "add_joint", id: "bottom_in_side_l", type: "groove", host: "drawer_side_l", guest: "drawer_bottom", depth: "5" },
    { op: "add_joint", id: "bottom_in_side_r", type: "groove", host: "drawer_side_r", guest: "drawer_bottom", depth: "5" },
    { op: "add_joint", id: "bottom_in_box_front", type: "groove", host: "drawer_box_front", guest: "drawer_bottom", depth: "5" },
    { op: "add_joint", id: "bottom_in_box_back", type: "groove", host: "drawer_box_back", guest: "drawer_bottom", depth: "5" },
    { op: "add_joint", id: "front_to_box", type: "screws", host: "false_front", guest: "drawer_box_front", count: 4 },
    {
      op: "set_hardware",
      id: "slides",
      kind: "drawer_slide",
      name: "Side-mount slide pair, 450 mm",
      connects: ["drawer_side_l", "drawer_side_r", "bottom"],
      qty: 1,
      spec: { clearance_per_side_mm: 12.7, length_mm: 450, load_kg: 45 },
    },
    {
      op: "set_array",
      id: "drawers_row",
      parts: ["false_front", "drawer_side_l", "drawer_side_r", "drawer_box_front", "drawer_box_back", "drawer_bottom"],
      axis: "x",
      count: "drawers",
      pitch: "bay + partition.thickness",
    },
    {
      op: "set_rule",
      id: "lp_fit",
      expr: "drawer_side_r.left - drawer_side_l.right >= lp_clear",
      severity: "error",
      message: "12-inch LPs need at least lp_clear inside each drawer",
    },
  ];
}
